import { format } from "date-fns";
import { Eye, Clock, CheckCircle, AlertCircle, Loader2, Sparkles, Bot } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { getStatusDisplay, getStatusColor } from "@/lib/utils/statusMapping";
import { LabAssignmentStatus } from "@prisma/client";

interface LabResult {
  id: number;
  resultDate: string;
  resultGeneratedBy: string;
  resultName: string;
  reports: {
    name: string;
    pdfUrl: string;
    values: string;
    analysisStatus?: string | null;
    analysisId?: number | null;
    hasAnalysis?: boolean;
  }[];
  phlebotomist?: string;
  labAssignmentId?: number;
  status?: string;
  hasAnyPendingAnalysis?: boolean;
  reportAnalyses?: any[];
}

const getStatusIcon = (status: string) => {
  switch (status) {
    case "COMPLETED":
      return <CheckCircle className="w-5 h-5 text-green-600" />;
    case "ANALYZING":
    case "IN_LAB":
    case "SAMPLE_COLLECTED":
      return <Clock className="w-5 h-5 text-blue-600" />;
    case "PENDING":
    case "ASSIGNED":
      return <Clock className="w-5 h-5 text-yellow-600" />;
    default:
      return <AlertCircle className="w-5 h-5 text-gray-600" />;
  }
};

const getStatusText = (status: string) => {
  switch (status) {
    case "COMPLETED":
      return "Completed";
    case "ANALYZING":
      return "Analyzing";
    case "IN_LAB":
      return "In Lab";
    case "SAMPLE_COLLECTED":
      return "Sample Collected";
    case "PENDING":
      return "Pending";
    case "ASSIGNED":
      return "Assigned";
    default:
      return "Unknown";
  }
};

interface LabResultCardProps {
  result: LabResult;
  onViewAnalysis?: (result: LabResult) => void;
}

export default function LabResultCard({ result, onViewAnalysis }: LabResultCardProps) {
  const firstReportPdfUrl = result.reports?.[0]?.pdfUrl;

  return (
    <div className="bg-white shadow-md rounded-3xl p-6">
      <div className="flex items-start justify-between">
        <div className="pr-3">
          <p className="text-lg font-bold text-primary">{result.resultName}</p>
          <p className="text-sm text-gray-500">Generated by: {result.resultGeneratedBy}</p>
          <p className="text-sm text-gray-400">
            Date: {format(new Date(result.resultDate), "dd/MM/yyyy")}
          </p>
          {result.phlebotomist && (
            <p className="text-sm text-gray-400">
              Phlebotomist: {result.phlebotomist}
            </p>
          )}
        </div>
        {result.status && (
          <Badge className={getStatusColor(result.status as LabAssignmentStatus)}>
            {getStatusDisplay(result.status as LabAssignmentStatus, 'pathology')}
          </Badge>
        )}
      </div>

      <div className="mt-6">
        <p className="text-lg font-bold text-gray-800">Reports</p>
        {result.reports.length > 0 ? (
          <div className="flex overflow-x-auto space-x-4 mt-4 pb-2 scrollbar-hide">
            {result.reports.map((report, index) => (
              <div key={index} className="bg-custom-mutedgreen p-4 rounded-lg flex flex-col items-center min-w-[200px] relative">
                <p className="text-lg font-bold text-gray-800 text-center">{report.name}</p>
                
                {/* Analysis Status Badge */}
                {report.analysisStatus && (
                  <div className="mt-2">
                    {report.analysisStatus === 'PENDING' && (
                      <Badge variant="outline" className="bg-yellow-50 text-yellow-700 border-yellow-200 text-xs">
                        <Clock className="w-3 h-3 mr-1" />
                        Analysis Pending
                      </Badge>
                    )}
                    {report.analysisStatus === 'PROCESSING' && (
                      <Badge variant="outline" className="bg-blue-50 text-blue-700 border-blue-200 text-xs">
                        <Loader2 className="w-3 h-3 mr-1 animate-spin" />
                        Analyzing...
                      </Badge>
                    )}
                    {report.analysisStatus === 'COMPLETED' && report.hasAnalysis && (
                      <Badge variant="outline" className="bg-green-50 text-green-700 border-green-200 text-xs">
                        <Sparkles className="w-3 h-3 mr-1" />
                        Analysis Ready
                      </Badge>
                    )}
                    {report.analysisStatus === 'FAILED' && (
                      <Badge variant="outline" className="bg-red-50 text-red-700 border-red-200 text-xs">
                        <AlertCircle className="w-3 h-3 mr-1" />
                        Analysis Failed
                      </Badge>
                    )}
                  </div>
                )}
                
                <a
                  href={report.pdfUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-secondary hover:underline text-sm mt-2"
                >
                  <Eye className="w-5 h-5 ml-1" />
                </a>
              </div>
            ))}
          </div>
        ) : (
          <p className="text-gray-500 mt-4">Reports are not available at the moment.</p>
        )}
      </div>

      {/* Action Buttons - consistent with StandaloneReportCard */}
      <div className="flex gap-2 mt-4">
        <Button
          variant="outline"
          size="sm"
          onClick={() => firstReportPdfUrl && window.open(firstReportPdfUrl, "_blank")}
          disabled={!firstReportPdfUrl}
          className="flex-1"
        >
          <Eye className="w-4 h-4 mr-2" />
          View Report
        </Button>
        <Button
          variant="default"
          size="sm"
          onClick={() => onViewAnalysis?.(result)}
          className="flex-1"
        >
          <Bot className="w-4 h-4 mr-2" />
          View Analysis
        </Button>
      </div>
    </div>
  );
}